### ISSUE TITLE
Decoding umlauts

### ISSUE THREAD

**Issue by hvbargen** [NaturalHistoryMuseum/pyzbar#14]
The zbar library obviously has problems with data containing non-ascii symbols, eg. german umlauts (ä ö ü).

I tried to decode the longer text from the QR-Code at https://de.wikipedia.org/wiki/QR-Code.

The result is:
b'Wikipedia ist ein Projekt zum Aufbau einer Enzyklop\xef\xbe\x83\xef\xbd\xa4die aus freien Inhalten in \xef\xbe\x83\xef\xbd\xbcber 270 Sprachen, zu dem du mit deinem Wissen beitragen kannst.'

This should be "Enzyklopädie" and "in über 270 Sprache".

Trying to decode with utf-8, this gives:

'Wikipedia ist ein Projekt zum Aufbau einer Enzyklopﾃ､die aus freien Inhalten in ﾃｼber 270 Sprachen, zu dem du mit deinem Wissen beitragen kannst.'

This does the trick: decode with utf-8, encode with shift-jis, and then decode with utf-8 again:

>>> data.decode("utf-8").encode("shift-jis").decode("utf-8")
'Wikipedia ist ein Projekt zum Aufbau einer Enzyklopädie aus freien Inhalten in über 270 Sprachen, zu dem du mit deinem Wissen beitragen kannst.'

I thought I'll add this as an issue to help others.

**Comment by quicklizard99** [comment]
Interesting. Thanks for the information. Some more reading about this:
* https://sourceforge.net/p/zbar/discussion/664596/thread/ed7aca9d/
* https://stackoverflow.com/questions/13395311/ios-zbar-sdk-unicode-characters
* https://sourceforge.net/p/zbar/support-requests/21/

I will close this issue as the behaviour is out of pyzbar's control.
