### ISSUE TITLE
new 'rect' attribute issues (Multiple)

### ISSUE THREAD

**Issue by oleg-petcov** [NaturalHistoryMuseum/pyzbar#17]
Version sync issue (I think)

If you do:
_'pip install pyzbar'_ 

you do not the latest pyzbar version that contains the 'rect' locations stuff

If you manually do an install with something like: 
_'pip install https://github.com/NaturalHistoryMuseum/pyzbar.git'_

you will have missing dependencies for the dll files 'libiconv' and 'libzbar'

I think this is a minor issue, but it was kind of annoying.

How to get around this issue for noobs such as myself:

1. Do a (fresh) _'pip install pyzbar'_ 
2. Then I copied the dll files from my 'C:\Users\<USERNAME>\Anaconda3\Lib\site-packages\pyzbar'
3.  _'pip uninstall pyzbar'_, to get rid of the version that did not contain the 'rect' changes
4. _'pip install pyzbar'_ , then proceed to copy the dll files back into the '/site-packages/pyzbar' folder

**Comment by quicklizard99** [comment]
The location stuff has only just been added to `pyzbar`. It will be available on PyPI when I release a new version of `pyzbar` - within the next week or so.

Glad that you managed to install from github!

**Comment by oleg-petcov** [comment]
Yeah it was a bit of a trivial thing, I just wanted to add it in for anyone else that may have issues.

It took me FOREVER to find a QR code tracker for OpenCV that's usable in Python, not too many examples around unfortunately.

Cheers for all the work!

**Comment by quicklizard99** [comment]
`0.1.5`, including barcode locations, now on PyPI.

**Comment by quicklizard99** [comment]
PS Thanks very much for the kind comment - very good to know that the package is turning out to be useful.
