### ISSUE TITLE
Polygons around barcodes

### ISSUE THREAD

**Issue by quicklizard99** [NaturalHistoryMuseum/pyzbar#21]
In addition to bounding boxes, make available a list of points describing the polygon around the barcode. Requested by @poynting (see #11)

**Comment by quicklizard99** [comment]
@poynting I think change will satisfy the requirement - please see the associated pull request (#22)

**Comment by poynting** [comment]
This looks good to me and works for my needs. Thanks!

**Comment by poynting** [comment]
Hi @quicklizard99 - do you have a time frame for your 1.6 release?  This is working great for our needs, and we would like to release some code dependent upon it.  The two environments I can test under are 

Python 3 / Windows 10 / Anaconda 
Python 2.7 / Ubuntu 14.04 

and both of these work with this branch.  If there's more that I can help with preparing for release, let me know.

**Comment by quicklizard99** [comment]
Hi @poynting - apologies for the delay in getting this out. Thanks very much for the testing and feedback. I will try to get a release within the next week.

**Comment by quicklizard99** [comment]
@poynting 0.1.7 now on PyPI
