### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by stepanvanzuriak** [NaturalHistoryMuseum/pyzbar#23]
I can't deploy app with pyzbar to heroku

_raise ImportError('Unable to find zbar shared library')_

Try use https://github.com/generalui/heroku-buildpack-zbar/tree/master/bin

**Comment by joshfriend** [comment]
I used [the apt buildpack](https://github.com/heroku/heroku-buildpack-apt) to install zbar, and the `.so` is in `LD_LIBRARY_PATH`:

```
$ echo $LD_LIBRARY_PATH 
/app/.heroku/vendor/lib:/app/.heroku/python/lib:/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib/i386-linux-gnu:/app/.apt/usr/lib:     
~ $ ls /app/.apt/usr/lib/x86_64-linux-gnu/
ImageMagick-6.8.9/          libMagick++-6.Q16.so        libv4l/                     libv4l2.so.0                libv4lconvert.so.0          libzbar.so                  pkgconfig/                  
libMagick++-6.Q16.a         libMagick++-6.Q16.so.5      libv4l1.so.0                libv4l2.so.0.0.0            libv4lconvert.so.0.0.0      libzbar.so.0                
libMagick++-6.Q16.la        libMagick++-6.Q16.so.5.0.0  libv4l1.so.0.0.0            libv4lconvert0/             libzbar.a                   libzbar.so.0.2.0
```

but `find_library('zbar')` returns `None`.

Oddly enough, this does work:

```python
>>> ctypes.CDLL('libzbar.so')
<CDLL 'libzbar.so', handle d22430 at 0x7f41faaf0c50>
```

**Comment by stepanvanzuriak** [comment]
I solve it, with changing `find_library` just to path at `/app/.apt/usr/lib/x86_64-linux-gnu/`

**Comment by joshfriend** [comment]
I think he's saying he hard coded the path to the library.

This change allows pyzbar to work on heroku, though it seems to prevent it from working in other cases: https://github.com/CptSpaceToaster/pyzbar/commit/5af0001506d39da1873f30de61c5ed5983927d70

**Comment by stepanvanzuriak** [comment]
@huubi52  Yes, @joshfriend  right. I just clone pyzbar on my project and hard coded path to library

**Comment by huubi52** [comment]
That works for me.
Thank you for helping me

**Comment by joshfriend** [comment]
pretty sure the issue is not fixed

**Comment by stepanvanzuriak** [comment]
I think it's not issue of pyzbar, but specific way in heroku to install packages

**Comment by Copser** [comment]
Hey, I just solved it by using [heroku-buildpack-apt](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt), you create Aptfile and add

```
libzbar0
libzbar-dev
```

it should fix the issue, also there is a [build pack](https://elements.heroku.com/buildpacks/generalui/heroku-buildpack-zbar) for zbar.

**Comment by kuznetsov-m** [comment]
thank you so much @Copser !
It best solution for me!

I could not solve the problem for a very long time... I am trying to use pyzbar on heroku. My app.py consists of one line:
`from pyzbar.pyzbar import decode`
But heroku tells me that
`ImportError: Unable to find zbar shared library`

Once again for everyone who ran into my problem. Here is a list of steps to run pyzbar on heroku:
1. Create heroku app
2. Create next files:
app.py
`from pyzbar.pyzbar import decode`
Procfile,
`main: python app.py`
requirements.txt
`pyzbar==0.1.8`
Aptfile
`libzbar-dev`
3. And add next buildpacks:
`https://github.com/heroku/heroku-buildpack-apt.git`
`heroku/python`
4. Push files and run app on heroku

**Comment by bakhrullo** [comment]
@kuznetsov-m  
thank you very much for helping me a lot
