### ISSUE TITLE
Failed to load dynlib/dll  libiconv.dll

### ISSUE THREAD

**Issue by ArP2018** [NaturalHistoryMuseum/pyzbar#27]
I am using pyinstaller script to pack my program. The pyinstaller script run without errors. However, when I ran my exe file which is produced by pyinstaller script, I got the error:
__main__.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\evyin\\AppData\\Local\\Temp\\_MEI18~1\\pyzbar\\libiconv.dll'. Most probably this dynlib/dll was not found when the application was frozen.
My environment: Python 3.5,  win10 64bit

**Comment by r92546024** [comment]
You can put the libiconv.dll & libzbar-64.dll in the exe work directory.
The exe file will use the dll in the same directory by first

**Comment by quicklizard99** [comment]
Freezers such as pyinstaller and cx_Freeze are not able to find libraries loaded using [ctypes](https://docs.python.org/3.6/library/ctypes.html). pyzbar exposes its binary dependencies in `EXTERNAL_DEPENDENCIES` - a list of instances of `ctypes.CDLL`. You can hack these into a pyinstaller freeze - e.g., via a [pyinstaller spec file](https://github.com/NaturalHistoryMuseum/inselect/blob/196a3ae2a0ed4e2c7cb667aaba9a6be1bcd90ca6/inselect.spec#L36).

Hope this helps!

**Comment by UsetIT** [comment]
The problem is I'm doing all of these, and combining all of these plus tons of answers from chatgpt and still no solution!
