### ISSUE TITLE
Where is the data in the project?

### ISSUE THREAD

**Issue by yueyueyijingxun** [NaturalHistoryMuseum/pyzbar#28]
First of all, sorry to ask such a simple question. I'm in a hurry to find the all data with binary. The whole pyzbar is a big project, and I have spent half past month to find it but no progress yet indeed. The reason why I want to find the real data is that I did something in the encoding process of QRcode, and now I should decode QRcode to get the data before analyze it. I know the decode function in pyzbar.py will return the results include data. I have found that _pixel_data function returns pixel, height and width as the following picture.
![image](https://user-images.githubusercontent.com/24663347/38920841-d5a7e4c2-4326-11e8-8870-72403551281e.png)
Then I use debugger to found the data, but it's sad that I didn't found the all data in debugger. There are too many new things that I couldn't understand in a short time. **Where is the all binary data in the project? Does the following picture realize that translate the binary data into character data? If not ,where should I find the binary data?**
![image](https://user-images.githubusercontent.com/24663347/38921578-ba8e4558-4328-11e8-8e8c-88d22e2a0190.png)
I am deeply appreciate any help from you!
PS: a debugger picture that I lost in
![image](https://user-images.githubusercontent.com/24663347/38922294-6e27b04e-432a-11e8-93ba-ed403b3fb657.png)

**Comment by quicklizard99** [comment]
Hi!

Sorry to hear that you have had problems getting pyzbar to work. Apologies but I am not able to understand the nature of the problem.

Please post a code fragment that reproduces the problem, together with the exception and stack trace that Python generates. For example:

```
from pyzbar.pyzbar import decode
from PIL import Image
decode('I am not an image')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lawrence/projects/pyzbar/pyzbar/pyzbar.py", line 182, in decode
    pixels, width, height = _pixel_data(image)
  File "/Users/lawrence/projects/pyzbar/pyzbar/pyzbar.py", line 147, in _pixel_data
    pixels, width, height = image
ValueError: too many values to unpack (expected 3)
```

**Comment by yueyueyijingxun** [comment]
Well, thank you for reply.

There is no problem in code running process. I once have the error that you showed, but it doesn't make sense for me now.

**I have solved the first question.** I already found the data from pixels  and convert it to binary data in debug mode. 
`pixels = image.tobytes()`
`width, height = image.size`
`pixels1 = ''.join([bin(ord(c)).replace('0b', '') for c in pixels])`

I realized that the binary data  include function area, so I can't separate it to two parts then decode them easily. The whole project based on zbar dll, so I have to change the zbar source code if I divided the code into two pieces and also want to decode them correctly. **Can you tell me how much you know the dll? It will be kind of you to tell me the dll source code that the project based?** If you understand what I am going to do, any suggestions are welcome and thankful!

**Comment by quicklizard99** [comment]
> ```
> pixels = image.tobytes()
> width, height = image.size
> pixels1 = ''.join([bin(ord(c)).replace('0b', '') for c in pixels])
> ```

You should not need to do this in order to get pixel data. What type of object is `image`? Could you post a code fragment showing how `image` is created?

> Can you tell me how much you know the dll? It will be kind of you to tell me the dll source code that the project based?
Aha! I understand the question. `pyzbar` (this project) is a Python interface to the `zbar` library, which provides the DLL that decodes the barcodes. The source code for `zbar` (and hence the DLL) is at http://zbar.sourceforge.net/. The two projects are independent of one another. I have not worked on `zbar`.

**Comment by yueyueyijingxun** [comment]
OK, I know how to solve my question after thinking for a long time. Sorry to trouble you and thank you for your patience!

**Comment by malfarizit** [comment]
> OK, I know how to solve my question after thinking for a long time. Sorry to trouble you and thank you for your patience!

how to solve this problem sir?
can you show me how?
