### ISSUE TITLE
Adding HiQ and JABCode to the mix

### ISSUE THREAD

**Issue by DonaldTsang** [NaturalHistoryMuseum/pyzbar#45]
## Introduction
JABCode is a color barcode used by the German government (Federal Office of Information Security) for tagging items. Currently there is no easy-to-use solutions available for the public to test and experiment. It is written in C

HiQ is a color barcode based on QR code, created by the students Hong Kong Chinese University (the top University of Hong Kong). It is written in Java

## Proposal
Inclusion of JABCode and HiQ color barcode creators and readers, and either add or adapt those repos into a neat Python package.

### For JABCode
* Repo https://github.com/jabcode/jabcode
* Website https://jabcode.org/
* Standard https://www.bsi.bund.de/EN/Publications/TechnicalGuidelines/TR03137/TechnicalGuidelines_03137_node.html
### For HiQ
* Repo https://github.com/ouyangzhibo/HiQ-Robust-and-Fast-Decoding-of-High-Capacity-Color-QR-Codes
* Website http://authpaper.net/

**Comment by quicklizard99** [comment]
It would be great to include support for these symbologies. However `pyzbar` does not itself decode barcodes - it is merely a wrapper around the `zbar` library (http://zbar.sourceforge.net), which does the hard work. Your request would better be directed to the maintainers of `bar` but unfortunately it has not been maintained for about ten years.

**Comment by DonaldTsang** [comment]
@quicklizard99 sorry about the bad news.
