### ISSUE TITLE
attribute error:'list' object has no attribute 'rect'

### ISSUE THREAD

**Issue by Thyagutamizhan** [NaturalHistoryMuseum/pyzbar#52]
error:
Traceback (most recent call last):
  File "C:/Users/Dell/Projects/open_cv/test_barcode.py", line 94, in <module>
    x,y,w,h=barcodes.rect
AttributeError: 'list' object has no attribute 'rect'

Process finished with exit code 1

**Comment by quicklizard99** [comment]
The `decode` function returns a list (https://github.com/NaturalHistoryMuseum/pyzbar/#example-usage). If you are absolutely sure that the software will always find exactly one barcode:

```
z, y, w, h = barcodes[0].rect
```

Your code will be more robust if it accommodates zero or more barcodes e.g.,

```
for barcode in barcodes:
    rect = barcode.rect
```
