### ISSUE TITLE
For people having issues importing DLLs when having pip == 20.0.0 or 20.0.1

### ISSUE THREAD

**Issue by studioj** [NaturalHistoryMuseum/pyzbar#73]
Its not a pyzbar issue but this was the best location i could think of posting this debug information.

PIP version 20.0.1 and version 20.0.0 have this issue
see this issue
https://github.com/pypa/pip/issues/7636

pip is not installing the right wheels

to resolve do
`python -m pip install pip==19.3.1`
edit: 
  the issue now has been fixed in pip
  so you can also do 

`python -m pip install pip --upgrade`

and then

`python -m pip uninstall pyzbar`
`python -m pip install pyzbar`

**Comment by Swoy** [comment]
Hello,

I followed your instruction, but I still get
FileNotFoundError: Could not find module 'libiconv.dll' (or one of its dependencies). Try using the full path with constructor syntax.
and
FileNotFoundError: Could not find module 'MY\PATH\.venv\lib\site-packages\pyzbar\libzbar-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

I installed zbar before I did this. 

Any ideas?

**Comment by davidburesund** [comment]
Hi @Swoy, I experienced the same issue as you and solved it by following the instructions at https://github.com/NaturalHistoryMuseum/pyzbar/issues/13#issuecomment-372104020.

> This is almost certainly because a runtime dependency of one of the DLLs (`libzbar-64.dll` or `libiconv.dll` on a 64-bit build of Python; `libzbar-32.dll` or `libiconv-2.dll` on a 32-bit build) was not found on your system. This will be hard to diagnose precisely without more information but I would guess that the expected Microsoft Visual C runtime DLL is missing from your system.
> 
> Could you install this from https://www.microsoft.com/en-US/download/details.aspx?id=40784 and try again?

**Comment by studioj** [comment]
Issue can be closed since it was actually a pip issue
